# Generated by Django 4.1.7 on 2023-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourdest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
