# Generated by Django 4.1.7 on 2023-04-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tourdest", "0002_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="employees",
        ),
    ]
