# Generated by Django 4.1.7 on 2023-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourdest", "0003_remove_shop_employees"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="products",
            field=models.ManyToManyField(
                through="tourdest.PaymentDetail", to="tourdest.product"
            ),
        ),
    ]
