# Generated by Django 4.1.7 on 2023-05-08 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tourdest", "0006_alter_payment_shop_alter_payment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopposition",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
