# Generated by Django 4.1.7 on 2023-05-09 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tourdest", "0008_alter_paymentdetail_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("-pk",)},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_type",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="products",
        ),
        migrations.AddField(
            model_name="payment",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tourdest.product",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tourdest.shop"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tourdest.shop"
            ),
        ),
        migrations.AlterField(
            model_name="shopposition",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tourdest.shop"
            ),
        ),
        migrations.DeleteModel(
            name="PaymentDetail",
        ),
    ]
