# Generated by Django 4.1.7 on 2023-05-09 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tourdest", "0010_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="quantity_reject",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tourdest.product"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
